### ISSUE TITLE
设置默认动画的时候就崩溃了

### ISSUE THREAD

**Issue by stay4cold** [LightSun/android-drag-FlowLayout#2]

**Comment by LightSun** [comment]
这周末我会处理下。

**Comment by LightSun** [comment]
能发下日志上来么

**Comment by stay4cold** [comment]
08-26 17:15:11.493 14663-14663/com.heaven7.android.drag.demo E/InputEventReceiver: Exception dispatching input event.
08-26 17:15:11.497 14663-14663/com.heaven7.android.drag.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.heaven7.android.drag.demo, PID: 14663
                                                                               java.lang.IllegalStateException: caused by targetIndex == -1
                                                                                   at com.heaven7.android.dragflowlayout.DragFlowLayout$InternalItemHelper.onRemoveView(DragFlowLayout.java:616)
                                                                                   at com.heaven7.android.dragflowlayout.DragFlowLayout.removeView(DragFlowLayout.java:470)
                                                                                   at com.heaven7.android.dragflowlayout.DefaultDragCallback.removeFromParent(DefaultDragCallback.java:79)
                                                                                   at com.heaven7.android.dragflowlayout.DefaultDragCallback.onRemoveView(DefaultDragCallback.java:72)
                                                                                   at com.heaven7.android.dragflowlayout.DragFlowLayout$InternalItemHelper.dispatchViewRemove(DragFlowLayout.java:585)
                                                                                   at com.heaven7.android.dragflowlayout.DragFlowLayout$InternalItemHelper.onRemoveView(DragFlowLayout.java:628)
                                                                                   at com.heaven7.android.dragflowlayout.DragFlowLayout.removeView(DragFlowLayout.java:470)
                                                                                   at com.heaven7.android.dragflowlayout.DragFlowLayout.processOverlap(DragFlowLayout.java:371)
                                                                                   at com.heaven7.android.dragflowlayout.DragFlowLayout.access$200(DragFlowLayout.java:29)
                                                                                   at com.heaven7.android.dragflowlayout.DragFlowLayout$2.onMove(DragFlowLayout.java:89)
                                                                                   at com.heaven7.android.dragflowlayout.AlertWindowHelper$DragTouchListener.onTouch(AlertWindowHelper.java:131)
                                                                                   at android.view.View.dispatchTouchEvent(View.java:8657)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2517)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2161)
                                                                                   at com.heaven7.android.dragflowlayout.DragFlowLayout.onTouchEvent(DragFlowLayout.java:504)
                                                                                   at android.view.View.dispatchTouchEvent(View.java:8668)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2517)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2161)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                                   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2523)
                                                                                   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2175)
                                                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2514)
                                                                                   at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1785)
                                                                                   at android.app.Activity.dispatchTouchEvent(Activity.java:2807)
                                                                                   at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2471)
                                                                                   at android.view.View.dispatchPointerEvent(View.java:8874)
                                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4729)
                                                                                   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4587)
                                                                                   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4086)
                                                                                   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4139)
                                                                                   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4105)
                                                                                   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4242)
                                                                                   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4113)
                                                                                   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4299)

**Comment by LightSun** [comment]
好的。周末我会统一处理。

**Comment by LightSun** [comment]
fixed .
